" Vundle!
set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My bundles
" LESS support
Bundle 'groenewege/vim-less'
" HAML support
Bundle 'tpope/vim-haml'
" Javscript support
Bundle 'pangloss/vim-javascript'
" Ruby helpers
Bundle 'vim-ruby/vim-ruby'
" Rails helpers
Bundle 'tpope/vim-rails'
" Cucumber support
Bundle 'tpope/vim-cucumber', {'rtp': 'vim/'}
" Auto add end keyword in ruby
Bundle 'tpope/vim-endwise'
" Nerdtree for project navigation
Bundle 'scrooloose/nerdtree'
" Syntax checks
Bundle 'scrooloose/syntastic'
" Fancy bottom bar
Bundle 'majutsushi/tagbar'
" Git helpers
Bundle 'tpope/vim-fugitive'
" Fuzzy file search
Bundle 'git://git.wincent.com/command-t.git'
" Autocomplete
Bundle 'Valloric/YouCompleteMe'
" Easy file searching
Bundle 'dkprice/vim-easygrep'
" Quick look ups of commands in dash
Bundle 'rizzatti/dash.vim'
" Add a gutter that shows git additions/deletions/etc
Bundle 'airblade/vim-gitgutter'

" CONFIGURATION

let mapleader = ","

" Pretty colours
syntax enable
" made_of_code
set background=dark
colorscheme molokai
" The default comment color is impossible to read
hi Comment         guifg=#A8A491

" Pretty fonts
set guifont=Inconsolata-dz\ for\ Powerline:h10

" Pretty status line
source /usr/local/lib/python2.7/site-packages/powerline/ext/vim/powerline.vim
set laststatus=2

" Indentation
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab

" Force the indentation to be correct when shifting
set shiftround

" Backspace through lines too
set backspace=indent,eol,start

" Ignore files I don't want to open in vim
set wildignore=*.o,*~,*.pyc,*.jpg,*.gif,*.png

" No trailing spaces
" See http://vim.wikia.com/wiki/Remove_unwanted_spaces
" Commented out because I think this is really slowing down my saves
" autocmd BufWritePre * :%s/\s\+$//e

" Make searching be incremental (e.g. search as you type)
set incsearch

" Show the matching brace when a new one is added
set showmatch

" More natural split opening position
set splitright

" Config for EasyGrep (project search within vim)
let g:EasyGrepCommand=1 " Use system grep instead of vim grep (required for excludes)
let g:EasyGrepRecursive=1 " Recursive search (slow!)
let g:EasyGrepFilesToExclude="*.log,tmp/*,coverage/*,tags,*.swp,*.swo"

" MAPPINGS

" Use ctrl-[hjkl] to select the active split!
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Move the splits arround!
" Doesn't work :(
"nmap <silent> <c-s-k> <C-W>K
"nmap <silent> <c-s-j> <C-W>J
"nmap <silent> <c-s-h> <C-W>H
"nmap <silent> <c-s-l> <C-W>L

" Open Nerd Tree
nmap <leader>n :NERDTree<cr>

" Open tagbar
nmap <leader>s :TagbarToggle<CR>

" Close current buffer
nmap <leader>q :bd<CR>

" Look up command in dash
nmap <silent> <leader>d :Dash<CR>

" Auto-reload the CommandT file list
augroup CommandTExtension
  autocmd!
  autocmd FocusGained * CommandTFlush
  autocmd BufWritePost * CommandTFlush
augroup END

" Autostrip trailing whitespace for certain filetypes
autocmd BufWritePre *.rb,*.js,*.feature :%s/\s\+$//e
