-- From https://github.com/crivotz/nv-ide/blob/e4e2c8a45eab9729a2ff119adbc0b43c36db3e8f/lua/plugins/lspkind.lua
require("lspkind").init({
	with_text = true,
	symbol_map = {
		Text = "",
		Method = "ƒ",
		Function = "",
		Constructor = "",
		Variable = "",
		Class = "",
		Interface = "ﰮ",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "了",
		Keyword = "",
		Snippet = "﬌",
		Color = "",
		File = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
	},
})
