export EDITOR=nvim

export PATH="/usr/local/sbin:$PATH"

# Show tmux window titles in tmux tabs
export DISABLE_AUTO_TITLE=true

# Homebrew on Apple Silicon is installed in a non-path location
if [[ $OSTYPE == darwin* && $CPUTYPE == arm64 ]]; then
	export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
fi


# Have to manually point to Postgres 15 binaries, see https://github.com/Homebrew/homebrew-core/issues/121043
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
