# APPEND_HISTORY If this is set, zsh sessions will append their history list to
# the history file, rather than replace it. Thus, multiple parallel zsh sessions
# will all have the new entries from their history lists added to the history
# file, in the order that they exit. The file will still be periodically
# re-written to trim it when the number of lines grows 20% beyond the value
# specified by $SAVEHIST (see also the HIST SAVE BY COPY option).
setopt APPEND_HISTORY

# Autocorrect was breaking too much stuff
unsetopt correct_all

RAILS_ENV=development
alias be="bundle exec"
alias bi="bundle install"
alias bu="bundle update"

alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias gc="git commit"
alias gch="git checkout"
alias gl="git lg"

# System VIM sucks and doesn't even have Python; use the one from MacVim
# Going to try using neovim
# alias vim="/Applications/MacVim.app/Contents/MacOS/Vim"
alias vim=nvim

alias upgradeall="brew update && brew upgrade && brew upgrade --cask --greedy && omz update && gem update --system && rvm get stable && rvm @global do gem update \`gem list | cut -d ' ' -f 1\` && rvm-update && yarn global upgrade --latest && npm update -g && vim -c 'BundleInstall! | q' && nvim -c 'call dein#update() | q'"

# https://gist.github.com/hlissner/db74d23fc00bed81ff62
function ag-replace() {
  ag -0 -l $1 | xargs -0 sed -ri.bak -e "s/$1/$2/g"
}

# Search for all files with contents using silver searcher,
# then open them in MacVim
function mvag() {
  vimr -p `ag -l $@`
}

# Search for all files with contents using silver searcher,
# then open them in Vim
function vag() {
  nvim -p `ag -l $@`
}

# Open all modified files in git
function mvgit() {
  nvimr -p $(git status -s | awk '{print $2}')
}

export EDITOR=nvim

# Shortcuts to jump forward/back a word with Alt+Arrow
bindkey '[C' forward-word
bindkey '[D' backward-word

# Show tmux window titles in tmux tabs
export DISABLE_AUTO_TITLE=true

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Secret environment variables - passwords etc.
if [ -f ~/.zshrcsecrets ]; then
  source ~/.zshrcsecrets
fi

export PATH="/usr/local/sbin:$PATH"

# Add pyenv to the path for management of Python versions
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.

# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=/Users/bmulholland/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="wezm"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew capistrano knife osx rails rake ruby rvm nvm git git-extras vagrant)

source $ZSH/oh-my-zsh.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
