# APPEND_HISTORY If this is set, zsh sessions will append their history list to
# the history file, rather than replace it. Thus, multiple parallel zsh sessions
# will all have the new entries from their history lists added to the history
# file, in the order that they exit. The file will still be periodically
# re-written to trim it when the number of lines grows 20% beyond the value
# specified by $SAVEHIST (see also the HIST SAVE BY COPY option).
setopt APPEND_HISTORY

# Autocorrect was breaking too much stuff
unsetopt correct_all

RAILS_ENV=development
alias be="bundle exec"
alias bi="bundle install"
alias bu="bundle update"

alias gs="git status"
alias gd="git diff"
alias gc="git commit"
alias gch="git checkout"
alias gl="git lg"

alias upgradeall="brew update && brew upgrade --all && upgrade_oh_my_zsh && vim -c 'BundleInstall!'"
