require("settings")
require("settings.plugins")
require("settings.keymap")
require("settings.font")
require("settings.colors")
require("settings.neovide")
require("settings.dap")

require("settings.scrolloff-fraction")

require("plugins.comment-nvim")
require("plugins.dark-notify")
require("plugins.diffview")
require("plugins.gitsigns")
require("plugins.indent-blankline")
require("plugins.lsp_signature")
require("plugins.lualine")
require("plugins.neogit")
require("plugins.nvim-autopairs")
require("plugins.nvim-cmp")
require("plugins.nvim-hlslens")
require("plugins.nvim-lightbulb")
require("plugins.nvim-neoclip")
require("plugins.nvim-ts-rainbow")
require("plugins.nvimtree")
require("plugins.project-nvim")
require("plugins.renamer-nvim")
require("plugins.telescope")
require("plugins.trouble")
require("plugins.todo-comments")
require("plugins.treesitter")
require("plugins.vim-gutentags")
require("plugins.vim-signature")
require("plugins.vim-ultest")
require("plugins.which-key")
require("plugins.wilder")

-- LSP Config
require("lsp")
