require('settings')
require('settings.keymap')
require('settings.font')
require('settings.plugins')
require('settings.colors')

require('settings.scrolloff-fraction')

require('plugins.airline')
require('plugins.dark-notify')
require('plugins.gitsigns')
require('plugins.lspkind')
require('plugins.numbertoggle')
require('plugins.nvim-autopairs')
require('plugins.nvim-compe')
require('plugins.nvim-lightbulb')
require('plugins.nvim-ts-rainbow')
require('plugins.nvimtree')
require('plugins.telescope')
require('plugins.todo-comments')
require('plugins.treesitter')
require('plugins.vim-gutentags')
require('plugins.vim-signature')
require('plugins.vim-sneak')

-- LSP Config
require('lsp')
